function student(name, age, classs) {
    this.name = name,
    this.age = age,
    this.classs = classs
}


var arr = {
    name: name = [
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
        'Ali',
        'Asad',
        'Akmal',
        'Fakhar',
    ],
    age: age = [
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
        11,
        12,
        13,
        14,
    ],
}


function dbs() {
    let success = document.createElement("p");
    success.style.color = "white";
    let ptext = document.createTextNode('Name ------' + '\t\t\t\t\t\t' + ' ---- Age');
    success.appendChild(ptext);
    document.body.appendChild(success);

    for(let i = 0; i < 59; i++){
    let success = document.createElement("p");
    success.style.color = "white";
    let ptext = document.createTextNode(arr.name[i] + " --------- \t\t\t\t\t\t ---------- " + arr.age[i]);
    success.appendChild(ptext);
    document.body.appendChild(success);
}
}